[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=8.1.0"]
build-backend = "setuptools.build_meta"

[tool.ruff.lint]
select = ["E"]
line-length = 100

[tool.setuptools_scm]
# write_to = "pymeasure/_version.py"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"